### ISSUE TITLE
`body` selector

### ISSUE THREAD

**Issue by aubreywullschleger** [deanarron/prj-rev-bwfs-dasmoto#4]
Great! Great use of the `body` selector in your CSS. The use of the `body` selector helps keep your CSS concise especially when using inherited styles on the selector as you've done with `font-family: Helvetica;` here.

https://github.com/deanarron/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L1-L3

Here, I would consider using a group selector for the `font-weight: bold;` style to make your CSS even more concise.

**Comment by deanarron** [comment]
Great, added a bold class for added neatness.
