### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [deanarron/prj-rev-bwfs-dasmoto#5]
Grade: Meets expectations

Summary:
Nice job on this project! I like that your HTML is consistently nested and indented, your use of `class` attributes, your use of descriptive `alt` attributes, and your use of the `body` selector in CSS.

One thing to work on would be using a group selector for the `font-weight: bold;` style in your CSS.

Next, as a stretch goal, I challenge you to research and implement media queries to make your page completely responsive for all screen widths. This is a challenge I think you are ready for based on your work here! Here are a couple resources to get you started: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by deanarron** [comment]
Thanks Aubrey! The review and suggestions are appreciated!
